apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  labels:
    app.kubernetes.io/instance: apiconnect
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: apiconnect-minimum
  name: apim-demo
  namespace: tools
spec:
  license:
    accept: true
    use: nonproduction
    metric: VIRTUAL_PROCESSOR_CORE
    license: L-RJON-C7BJ42
  profile: n1xc7.m48
  version: 10.0.4.0-ifix3
  storageClassName: ibmc-block-gold
  endpointTypes:
    - APIs
    - Events
  management:
    analytics:
      client: {}
      ingestion: {}
    apiManagerEndpoint: {}
    portal:
      admin: {}
    cloudManagerEndpoint: {}
    testAndMonitor:
      enabled: true
      hubEndpoint: {}
      turnstileEndpoint: {}
    consumerAPIEndpoint: {}
    billing:
      enabled: true
    platformAPIEndpoint: {}
    databaseBackup:
      restartDB:
        accept: false
    originalUID: ''
  gateway:
    openTracing:
      enabled: true
      odTracingNamespace: tools
      imageAgent: >-
        cp.icr.io/cp/icp4i/od/icp4i-od-agent:2.5.6-amd64@sha256:8c808d1b54664eda44b7b54e4a7af89e12f6e701baf69b1d6e752704448f0305
      imageCollector: >-
        cp.icr.io/cp/icp4i/od/icp4i-od-collector:2.5.6-amd64@sha256:d3934be22d88e11f9512f878d6ac05f2d29e40be7cee0b39c4b455ff786aba76
      odTracingDataHostname: od-store-od.tools.svc
      odTracingNamespace: tools
      odTracingRegistrationHostname: icp4i-od.tools.svc
    podAutoScaling:
      method: HPA
      hpa:
        minReplicas: 1
        maxReplicas: 3
        targetCPUUtilizationPercentage: 10